# Generated by Django 5.2.5 on 2025-08-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_image_bookimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/images/'),
        ),
        migrations.DeleteModel(
            name='BookImage',
        ),
    ]
