# Generated by Django 5.2.5 on 2025-08-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_image_bookimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookimage',
            old_name='product',
            new_name='book',
        ),
    ]
